#!/usr/bin/env python3
"""Compiles the vanilla 1.20.1 worldgen JSON (see fetch_vanilla.py) into compact Luau data modules.

    python tools/fetch_vanilla.py
    python tools/build_data.py            # writes src/TerrainGenerator/Data/*.luau

The generated modules contain *data only*.  All behaviour lives in hand-written modules.
"""
from __future__ import annotations

import json
import math
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
CACHE = ROOT / ".cache" / "vanilla"
OUT = ROOT.parent / "src" / "TerrainGenerator" / "Data"

# --------------------------------------------------------------------------------------
# Lua serialisation
# --------------------------------------------------------------------------------------
_IDENT = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
_LUA_KEYWORDS = {"and", "break", "do", "else", "elseif", "end", "false", "for", "function", "if", "in",
                 "local", "nil", "not", "or", "repeat", "return", "then", "true", "until", "while", "continue"}


def lua_num(v) -> str:
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, int):
        return str(v)
    if v == int(v) and abs(v) < 1e15:
        return str(int(v)) if v == int(v) else repr(v)
    return repr(float(v))


def lua(obj) -> str:
    if obj is None:
        return "nil"
    if isinstance(obj, bool):
        return "true" if obj else "false"
    if isinstance(obj, (int, float)):
        return lua_num(obj)
    if isinstance(obj, str):
        return json.dumps(obj, ensure_ascii=True)
    if isinstance(obj, (list, tuple)):
        return "{" + ",".join(lua(v) for v in obj) + "}"
    if isinstance(obj, dict):
        parts = []
        for k, v in obj.items():
            if v is None:
                continue
            if isinstance(k, str) and _IDENT.match(k) and k not in _LUA_KEYWORDS:
                parts.append(f"{k}={lua(v)}")
            else:
                parts.append(f"[{lua(k)}]={lua(v)}")
        return "{" + ",".join(parts) + "}"
    raise TypeError(type(obj))


def write_module(name: str, header: str, value) -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    path = OUT / f"{name}.luau"
    path.write_text(f"--!nocheck\n--!nolint\n-- GENERATED by tools/build_data.py -- do not edit.\n-- {header}\nreturn {lua(value)}\n")
    print(f"  {name}.luau  {path.stat().st_size / 1024:.1f} KB")


def load(kind: str, name: str):
    name = strip(name)
    return json.loads((CACHE / kind / f"{name}.json").read_text())


def strip(s: str) -> str:
    return s[len("minecraft:"):] if isinstance(s, str) and s.startswith("minecraft:") else s


# --------------------------------------------------------------------------------------
# Noise parameters
# --------------------------------------------------------------------------------------
def build_noise_params() -> dict:
    out = {}
    for p in sorted((CACHE / "noise").glob("*.json")):
        d = json.loads(p.read_text())
        out[p.stem] = [d["firstOctave"], d["amplitudes"]]
    return out


# --------------------------------------------------------------------------------------
# Density functions -> hash-consed node array
# --------------------------------------------------------------------------------------
class DensityBuilder:
    UNARY = {"abs", "square", "cube", "half_negative", "quarter_negative", "squeeze",
             "interpolated", "flat_cache", "cache_2d", "cache_once", "cache_all_in_cell"}
    BINARY = {"add", "mul", "min", "max"}

    def __init__(self):
        self.nodes: list[list] = []
        self.index: dict[str, int] = {}
        self.splines: list[list] = []
        self.spline_index: dict[str, int] = {}
        self.named: dict[str, int] = {}
        self.stack: list[str] = []

    # -- node creation ---------------------------------------------------------------
    def add(self, node: list) -> int:
        key = json.dumps(node)
        if key in self.index:
            return self.index[key]
        self.nodes.append(node)
        self.index[key] = len(self.nodes)  # 1-based
        return self.index[key]

    def const(self, v: float) -> int:
        return self.add(["const", float(v)])

    def is_const(self, i: int):
        n = self.nodes[i - 1]
        return n[1] if n[0] == "const" else None

    # -- resolution ------------------------------------------------------------------
    def ref(self, x) -> int:
        if isinstance(x, (int, float)):
            return self.const(x)
        if isinstance(x, str):
            name = strip(x)
            if name in self.named:
                return self.named[name]
            if name in self.stack:
                raise RuntimeError("cycle " + name)
            self.stack.append(name)
            i = self.build(load("density_function", name))
            self.stack.pop()
            self.named[name] = i
            return i
        return self.build(x)

    def build(self, d) -> int:
        if isinstance(d, (int, float, str)):
            return self.ref(d)
        t = strip(d["type"])
        if t == "constant":
            return self.const(d["argument"])
        if t in self.BINARY:
            a, b = self.ref(d["argument1"]), self.ref(d["argument2"])
            ca, cb = self.is_const(a), self.is_const(b)
            if ca is not None and cb is not None:
                v = {"add": ca + cb, "mul": ca * cb, "min": min(ca, cb), "max": max(ca, cb)}[t]
                return self.const(v)
            if t == "mul":
                if ca == 1.0:
                    return b
                if cb == 1.0:
                    return a
            # constants go second so the runtime can specialise "x op constant"
            if ca is not None and t in ("add", "mul", "min", "max"):
                a, b = b, a
            return self.add([t, a, b])
        if t == "blend_alpha":
            return self.const(1.0)
        if t == "blend_offset":
            return self.const(0.0)
        if t == "blend_density":
            return self.ref(d["argument"])
        if t in self.UNARY:
            return self.add([t, self.ref(d["argument"])])
        if t == "clamp":
            return self.add(["clamp", self.ref(d["input"]), d["min"], d["max"]])
        if t == "y_clamped_gradient":
            return self.add(["y_clamped_gradient", d["from_y"], d["to_y"], d["from_value"], d["to_value"]])
        if t == "noise":
            return self.add(["noise", strip(d["noise"]), d["xz_scale"], d["y_scale"]])
        if t == "shifted_noise":
            return self.add(["shifted_noise", strip(d["noise"]), d["xz_scale"], d["y_scale"],
                             self.ref(d["shift_x"]), self.ref(d["shift_y"]), self.ref(d["shift_z"])])
        if t in ("shift_a", "shift_b", "shift"):
            return self.add([t, strip(d["argument"])])
        if t == "weird_scaled_sampler":
            return self.add(["weird_scaled_sampler", self.ref(d["input"]), strip(d["noise"]),
                             strip(d["rarity_value_mapper"])])
        if t == "old_blended_noise":
            return self.add(["old_blended_noise", d["xz_scale"], d["y_scale"], d["xz_factor"], d["y_factor"],
                             d["smear_scale_multiplier"]])
        if t == "range_choice":
            return self.add(["range_choice", self.ref(d["input"]), d["min_inclusive"], d["max_exclusive"],
                             self.ref(d["when_in_range"]), self.ref(d["when_out_of_range"])])
        if t == "spline":
            return self.add(["spline", self.spline(d["spline"])])
        raise NotImplementedError(t)

    def spline(self, s) -> int:
        if isinstance(s, (int, float)):
            raise AssertionError("constants are stored inline")
        coord = self.ref(s["coordinate"])
        locs, vals, ders = [], [], []
        for p in s["points"]:
            locs.append(p["location"])
            ders.append(p["derivative"])
            v = p["value"]
            vals.append(float(v) if isinstance(v, (int, float)) else [self.spline(v)])
        entry = [coord, locs, vals, ders]
        key = json.dumps(entry)
        if key not in self.spline_index:
            self.splines.append(entry)
            self.spline_index[key] = len(self.splines)
        return self.spline_index[key]


def build_density(ns: dict) -> dict:
    b = DensityBuilder()
    router = {}
    for k, v in ns["noise_router"].items():
        router[k] = b.ref(v)
    print(f"  density nodes: {len(b.nodes)}, splines: {len(b.splines)}")
    return {"nodes": b.nodes, "splines": b.splines, "router": router}


# --------------------------------------------------------------------------------------
# Surface rules
# --------------------------------------------------------------------------------------
def norm(node):
    """Strips the minecraft: namespace everywhere and reduces block states to names."""
    if isinstance(node, dict):
        out = {}
        for k, v in node.items():
            if k == "result_state":
                out[k] = strip(v["Name"])
            elif k == "type":
                out[k] = strip(v)
            else:
                out[k] = norm(v)
        return out
    if isinstance(node, list):
        return [norm(v) for v in node]
    if isinstance(node, str):
        return strip(node)
    return node


# --------------------------------------------------------------------------------------
# Features
# --------------------------------------------------------------------------------------
class FeatureBuilder:
    def __init__(self):
        self.placed: dict[str, dict] = {}
        self.unsupported: dict[str, str] = {}

    @staticmethod
    def species_of(name: str) -> str:
        return re.sub(r"_bees_\d+$", "", strip(name))

    def cfg(self, ref, name_hint: str | None = None):
        if isinstance(ref, str):
            name = strip(ref)
            try:
                d = load("configured_feature", name)
            except FileNotFoundError:
                return None
            return self.cfg_body(d, name)
        return self.cfg_body(ref, name_hint)

    def cfg_body(self, d: dict, name: str | None):
        t = strip(d["type"])
        c = d.get("config", {})
        if t == "tree":
            tp = c.get("trunk_placer", {})
            return {"kind": "tree", "species": self.species_of(name or "tree"),
                    "h": [tp.get("base_height", 4), tp.get("height_rand_a", 2), tp.get("height_rand_b", 0)],
                    "trunk": strip(c["trunk_provider"]["state"]["Name"]) if "state" in c.get("trunk_provider", {}) else None}
        if t in ("huge_red_mushroom", "huge_brown_mushroom"):
            return {"kind": "tree", "species": t, "h": [4, 3, 0]}
        if t in ("ore", "scattered_ore"):
            return {"kind": "ore", "size": c["size"], "discard": c["discard_chance_on_air_exposure"],
                    "targets": [{"state": strip(x["state"]["Name"]), "target": norm(x["target"])} for x in c["targets"]],
                    "scattered": t == "scattered_ore" or None}
        if t == "disk":
            return {"kind": "disk", "radius": norm(c["radius"]), "halfHeight": c["half_height"],
                    "target": norm(c["target"]), "state": norm(c["state_provider"])}
        if t == "freeze_top_layer":
            return {"kind": "freeze"}
        if t == "random_selector":
            options = [{"chance": o["chance"], "feature": self.placed_ref(o["feature"], name)} for o in c["features"]]
            default = self.placed_ref(c["default"], name)
            if default is None and not any(o["feature"] for o in options):
                return None
            return {"kind": "pick", "options": [o for o in options if o["feature"]], "default": default}
        if t == "simple_random_selector":
            feats = [self.placed_ref(f, name) for f in c["features"]]
            if not any(feats):
                return None
            return {"kind": "any", "features": [f or {"placement": []} for f in feats]}
        if t == "random_boolean_selector":
            a, b = self.placed_ref(c["feature_true"], name), self.placed_ref(c["feature_false"], name)
            if a is None and b is None:
                return None
            return {"kind": "bool", "t": a, "f": b}
        self.unsupported[name or "?"] = t
        return None

    def placed_ref(self, ref, name_hint=None):
        if isinstance(ref, str):
            name = strip(ref)
            if name in self.placed:
                return {"ref": name}
            try:
                p = load("placed_feature", name)
            except FileNotFoundError:
                # a configured feature used where a placed feature is expected
                prog = self.cfg(ref, name)
                return {"placement": [], "feature": prog} if prog else None
            self.placed[name] = None  # cycle guard
            self.placed[name] = self.placed_body(p, name)
            return {"ref": name} if self.placed[name] is not None else None
        return self.placed_body(ref, name_hint)

    def placed_body(self, p: dict, name):
        prog = self.cfg(p["feature"], name)
        if prog is None:
            return None
        return {"placement": norm(p["placement"]), "feature": prog}


def build_biomes_and_features():
    fb = FeatureBuilder()
    biomes = {}
    wanted_carvers = set()
    for path in sorted((CACHE / "biome").glob("*.json")):
        d = json.loads(path.read_text())
        steps = []
        for step in d["features"]:
            names = []
            for f in step:
                n = strip(f)
                ref = fb.placed_ref(f)
                if ref is not None and "ref" in ref and fb.placed.get(ref["ref"]) is not None:
                    names.append(n)
            steps.append(names)
        carvers = [strip(c) for c in d.get("carvers", {}).get("air", [])]
        wanted_carvers.update(carvers)
        biomes[path.stem] = {
            "temperature": d["temperature"],
            "downfall": d["downfall"],
            "precipitation": d["has_precipitation"],
            "frozen": (d.get("temperature_modifier") == "frozen") or None,
            "carvers": carvers,
            "features": steps,
        }
    placed = {k: v for k, v in fb.placed.items() if v is not None}
    print(f"  biomes: {len(biomes)}, supported placed features: {len(placed)}")
    print("  ignored configured feature types:", sorted(set(fb.unsupported.values())))
    return biomes, placed, sorted(wanted_carvers)


def build_carvers(names):
    out = {}
    for n in names:
        d = load("configured_carver", n)
        out[n] = norm(d)
    return out


def main() -> int:
    if not CACHE.exists():
        print("run tools/fetch_vanilla.py first", file=sys.stderr)
        return 1
    ns = load("noise_settings", "overworld")
    print("building data modules")
    settings = {
        "minY": ns["noise"]["min_y"], "height": ns["noise"]["height"],
        "sizeHorizontal": ns["noise"]["size_horizontal"], "sizeVertical": ns["noise"]["size_vertical"],
        "seaLevel": ns["sea_level"], "aquifersEnabled": ns["aquifers_enabled"],
        "oreVeinsEnabled": ns["ore_veins_enabled"], "defaultBlock": strip(ns["default_block"]["Name"]),
        "defaultFluid": strip(ns["default_fluid"]["Name"]),
    }
    write_module("Settings", "noise_settings/overworld (scalars)", settings)
    write_module("NoiseParams", "worldgen/noise/*.json: {firstOctave, amplitudes}", build_noise_params())
    write_module("DensityFunctions", "noise router as a hash-consed DAG; ids are 1-based", build_density(ns))
    write_module("SurfaceRules", "noise_settings/overworld surface_rule", norm(ns["surface_rule"]))
    biomes, placed, carver_names = build_biomes_and_features()
    write_module("Biomes", "worldgen/biome/*.json (subset)", biomes)
    write_module("Features", "resolved placed features (ores, disks, trees, freeze)", placed)
    write_module("Carvers", "worldgen/configured_carver/*.json", build_carvers(carver_names))
    return 0


if __name__ == "__main__":
    sys.exit(main())
