#!/usr/bin/env python3
"""Bundles src/TerrainGenerator (+ a test entry file) into one Luau file for the standalone Luau CLI.

Roblox modules use `require(script.Parent.X)`.  The bundle wraps every module in
`function(script, require) ... end` with fake `script` instances so the exact same source runs
unmodified under `luau`.

    python tools/bundle.py tests/foo.luau build/foo.bundle.luau
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src"


def module_path(p: Path) -> str:
    rel = p.relative_to(SRC).with_suffix("")
    parts = list(rel.parts)
    if parts[-1] == "init":
        parts.pop()
    return "/".join(parts)


def clean(source: str) -> str:
    source = re.sub(r"^--!.*$", "", source, flags=re.M)          # file-level directives
    source = re.sub(r"^export type ", "type ", source, flags=re.M)  # export only valid at file top level
    return source


def main() -> int:
    entry = Path(sys.argv[1])
    out = Path(sys.argv[2])
    files = sorted(p for p in SRC.rglob("*.luau") if not p.name.endswith((".server.luau", ".client.luau")))
    lines = [
        "-- generated by tools/bundle.py",
        "local __defs, __cache, __nodes = {}, {}, {}",
        "local __methods = {",
        "  FindFirstChild = function(self, name) return self[name] end,",
        "  IsDescendantOf = function(self, other) local p = self.Parent while p do if p == other then return true end p = p.Parent end return false end,",
        "  Clone = function(self) if Instance then local c = Instance.new('ModuleScript') c.Name = self.Name return c end return self end,",
        "}",
        "local function __node(path)",
        "  local n = __nodes[path]",
        "  if n then return n end",
        "  n = {__path = path}",
        "  __nodes[path] = n",
        "  local parent = path:match('^(.*)/[^/]+$')",
        "  n.Name = path:match('([^/]+)$')",
        "  n.Parent = parent and __node(parent) or nil",
        "  return setmetatable(n, {__index = function(t, k)",
        "    local m = __methods[k]",
        "    if m then return m end",
        "    local child = path .. '/' .. k",
        "    if __defs[child] or __nodes[child] then return __node(child) end",
        "    for p in pairs(__defs) do if p:sub(1, #child + 1) == child .. '/' then return __node(child) end end",
        "    return nil end})",
        "end",
        "local function __require(inst)",
        "  local path = inst.__path",
        "  local c = __cache[path]",
        "  if c ~= nil then return c end",
        "  local def = __defs[path]",
        "  if not def then error('no module ' .. tostring(path)) end",
        "  local v = def(__node(path), __require)",
        "  __cache[path] = v == nil and true or v",
        "  return __cache[path]",
        "end",
    ]
    for p in files:
        lines.append(f"__defs[{module_path(p)!r}] = function(script, require)")
        lines.append(clean(p.read_text()))
        lines.append("end")
    # the entry file sees `script` as a sibling of TerrainGenerator, and a global `TG` helper
    lines.append("local script = __node('TestEntry')")
    lines.append("local require = __require")
    lines.append("local TG = __node('TerrainGenerator')")
    entry_src = entry.read_text()
    entry_src = re.sub(r"^--@include (\S+)$", lambda m: (ROOT / "tests" / m.group(1)).read_text(), entry_src, flags=re.M)
    lines.append(clean(entry_src))
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines))
    return 0


if __name__ == "__main__":
    sys.exit(main())
